imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fulldon.yml }
    - { resource: custom_fulldon.yml }

parameters:
# Certeurope
    certeurope_certisms_app_code: 8cea3aa7f7a70fe84560acd895b10fb70f883a6e
    certeurope_certisms_url: http://certisms.certeurope.fr/CertiSMS.php
    certeurope_certisms_wsdl: http://certisms.certeurope.fr/CertiSMS.php?wsdl
    certeurope_oneclick_app_code: 692d7e41849b50e4bd7eed4918f0da028b773707
    certeurope_oneclick_url: https://cs1.certeurope.fr/SignatureCOC.do
#Sms pro
    sms_url:        https://www.envoyersmspro.com/api/message/send
    sms_login:      '0650698945'
    sms_password:   '0365'
#Mandrill
    mandrill_api_key: q13eWdiWhPkpY28Z8Qv53A
#Emailing tags
    tag_notification: tag-notif
    tag_courrier: tag-courrier
    tag_rf: tag-rf
    tag_emarketing: tag-emarketing
    tag_new_password: tag-new-password
    tag_confirm_don: tag-confirm-don

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    globals:
        assoc_name: %assoc_name%
        url_site: %url_site%
        google_analytics_code: %google_analytics%
        tag_notification: %tag_notification%
        tag_courrier: %tag_courrier%
        tag_rf: %tag_rf%
        tag_emarketing: %tag_emarketing%
        tag_new_password: %tag_new_password%
        tag_confirm_don: %tag_confirm_don%
        tag_prefix: %prefix_tag%
        subscription_cb: %subscription_cb%
        subscription_online: %subscription_online%
        left_time: "@fulldon.intersa.global"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [FulldonSecurityBundle, FulldonAdminBundle, FulldonIntersaBundle, FulldonDonateurBundle, CustomFulldonExtDonateurBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: current
        connections:
            current:
                driver:    pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            fulldon:
                driver:    pdo_mysql
                host:     "%fulldb_host%"
                port:     "%fulldb_port%"
                dbname:   "%fulldb_name%"
                user:     "%fulldb_user%"
                password: "%fulldb_password%"
                charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        metadata_cache_driver: apc
        query_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }

jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: true

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }

ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            stylesSet: "my_styles"
            extraPlugins: "strinsert,emarketinginsert"
            allowedContent:  true

    styles:
        my_styles:
            - { name: "image mobile", element: "img", attributes: { class: "hidden-md" }}
            - { name: "image pc", element: "img", attributes: { class: "hidden-xs" }}
            - { name: "image fluid", element: "img", attributes: { class: "img-responsive" }}

#hip_mandrill:
#    api_key: %mandrill_api_key%
##    disable_delivery: false # useful for dev/test environment. Default value is 'false'
#    default:
#        sender: service-technique@intersa.fr
#        sender_name: %assoc_name%
#        subaccount: %subaccount%



#monolog:
#    handlers:
#        mail:
#            type:         fingers_crossed
#            action_level: critical
#            handler:      buffered
#        buffered:
#            type:    buffer
#            handler: swift
#        swift:
#            type:       swift_mailer
#            from_email: service-technique@intersa.fr
#            to_email:   boussacsou@intersa.fr
#            subject:    %subject_email_log%
#            level:      debug
            
            
            
monolog:
    handlers:
        main_critical:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered_critical
        buffered_critical:
            type:    buffer
            handler: swift_critical
        swift_critical:
            type:       swift_mailer
            from_email: service-technique@intersa.fr
            to_email:   turki@intersa.fr
            subject:    %subject_email_log%
            level:      debug

        main_error:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_error
        grouped_error:
            type:    group
            members: [streamed, buffered_error]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered_error:
            type:    buffer
            handler: swift_error
        swift_error:
            type:       swift_mailer
            from_email: service-technique@intersa.fr
            to_email:   turki@intersa.fr
            subject:    %subject_email_log%
            level:      debug
            
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []
     
        
        
        
    
    
#Mandrill
#    mandrill_api_key: eRKopOPmlK5410T_LEiq8Q
    
slot_mandrill:
    api_key: %mandrill_api_key%
    disable_delivery: false # useful for dev/test environment. Default value is 'false'
    # debug: passed to \Mandrill causing it to output curl requests. Useful to see output
    # from CLI script. Default value is 'false'
    debug: true
    default:
        sender: service-technique@intesa.fr
        sender_name: %assoc_name% 
        subaccount: %subaccount%
#    proxy:
#        use: true # when you are behing a proxy. Default value is 'false'
#        host: smtp.mandrillapp.com
#        port: 587
#        user: intersa
#        password: eRKopOPmlK5410T_LEiq8Q
            
#            
#white_october_pagerfanta:
#    exceptions_strategy:
#        out_of_range_page:        ~
#        not_valid_current_page:   ~

