<?php

namespace Fulldon\IntersaBundle\Entity;

/**
 * BillReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillReportRepository extends \Doctrine\ORM\EntityRepository
{
}
