<?php

namespace Fulldon\IntersaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourrierTraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DessinEnregistrementRepository extends EntityRepository
{
}
