<?php

namespace Fulldon\IntersaBundle\Entity;

/**
 * PersoaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoaRepository extends \Doctrine\ORM\EntityRepository
{
}
