<?php

namespace Fulldon\IntersaBundle\Entity;

/**
 * PersodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersodRepository extends \Doctrine\ORM\EntityRepository
{
}
