<?php

namespace Fulldon\IntersaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersoRfsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoRfsRepository extends EntityRepository
{
}
