parameters:
#    fulldon_admin.example.class: Fulldon\AdminBundle\Example

services:
#    fulldon_admin.example:
#        class: %fulldon_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
