<?php

namespace Fulldon\DonateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CauseRepository extends EntityRepository
{
    public function byCause($cause) {
        $qb = $this->createQueryBuilder('c')
                ->where('c.code LIKE :cause')
                ->setParameter('cause', '%' . $cause . '%');
        return $qb->getQuery()->getResult();
    }
}
