<?php

namespace Fulldon\DonateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateurRepository extends EntityRepository
{
     public function byEntreprise() {
//        $qb = $this->createQueryBuilder('s');
////                ->where('s.numSecu = :numerosecurite')
////                ->setParameter('numerosecurite', $numsecu);
//        return $qb->getQuery()->getResult();
    }
}
