<?php

namespace Fulldon\DonateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotifDisableDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifDisableDonRepository extends EntityRepository
{
}
