<?php

namespace Fulldon\DonateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReceptionModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionModeRepository extends EntityRepository
{
}
